title: <p align="center"> Rakesh Shah </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rakesh-shah-aa4a93102/">LinkedIn</a> |
  <a href="https://github.com/rakesh-shah">GitHub</a>
  
  <br>   
  With 6+ years of in depth experience in the field of Data Engineering ,DevOps - CICD - Jenkins , Building Cloud Infrastructure for AWS and GCP with excellent communication skills
  I have in depth knowledge of Big Data YARN and its processing.
  I have worked and have sound understanding of the various Big data tool stack like (Spark, Hadoop, Hive , Kafka).
  I am very well versed with cloud platform such as GCP and AWS.
  <br>
  </p>



theme: jekyll-theme-minimal